library(shiny)
library(ggplot2)

shinyUI(fluidPage(

    # Application title
    titlePanel("NCAA D-1A (FBS) Bowl Eligibility Modeling"),

    sidebarLayout(
        sidebarPanel(
            radioButtons("plotType", "Select Plot Type",
                         choices = c("Barplot of Total Wins per Conference" = 1,
                                     "Histogram (1 - variable)" = 2,
                                     "Scatterplot (2 - variable)" = 3,
                                     "Boxplot (2 - variable)" = 4)),
            
            conditionalPanel(
              condition = "input.plotType == 2",
              selectizeInput("x", "Select Variable",
                             choices = c("Yards per Game" = "totalYards",
                                         "Pass Attempts per Game" = "passAttempts",
                                         "Pass Completions per Game" = "passCompletions",
                                         "Net Passing Yards per Game" = "netPassingYards",
                                         "Passing TDs per Game" = "passingTDs",
                                         "Rush Attempts per Game" = "rushingAttempts",
                                         "Rushing Yards per Game" = "rushingYards",
                                         "Rushing TDs per Game" = "rushingTDs",
                                         "First Downs per Game" = "firstDowns",
                                         "Third Down Conversion Rate" = "thirdDownConversionRate",
                                         "Fourth Down Completion Rate" = "fourthDownConversionRate",
                                         "Turnover Differential" = "turnoverDiff",
                                         "Average Time of Possession (Seconds)" = "possessionTime",
                                         "Defense Tackles for Loss per Game" = "tacklesForLoss",
                                         "Defense Sacks per Game" = "sacks",
                                         "Interception Yards per Game" = "interceptionYards",
                                         "Interception TDs per Game" = "interceptionTDs",
                                         "Punt Returns per Game" = "puntReturns",
                                         "Punt Return Yards per Game" = "puntReturnYards",
                                         "Punt Return TDs per Game" = "puntReturnTDs",
                                         "Kick Returns per Game" = "kickReturns",
                                         "Kick Return Yards per Game" = "kickReturnYards",
                                         "Kick Return TDs per Game" = "kickReturnTDs",
                                         "Penalties per Game" = "penalties",
                                         "Penalty Yards per Game" = "penaltyYards")),
              sliderInput("bins", "Number of bins",
                          min = 5, max = 30, value = 15, step = 1)),
            conditionalPanel(
              condition = "input.plotType == 3",
              selectizeInput("x", "Select Variable",
                             choices = c("Yards per Game" = "totalYards",
                                         "Pass Attempts per Game" = "passAttempts",
                                         "Pass Completions per Game" = "passCompletions",
                                         "Net Passing Yards per Game" = "netPassingYards",
                                         "Passing TDs per Game" = "passingTDs",
                                         "Rush Attempts per Game" = "rushingAttempts",
                                         "Rushing Yards per Game" = "rushingYards",
                                         "Rushing TDs per Game" = "rushingTDs",
                                         "First Downs per Game" = "firstDowns",
                                         "Third Down Conversion Rate" = "thirdDownConversionRate",
                                         "Fourth Down Completion Rate" = "fourthDownConversionRate",
                                         "Turnover Differential" = "turnoverDiff",
                                         "Average Time of Possession (Seconds)" = "possessionTime",
                                         "Defense Tackles for Loss per Game" = "tacklesForLoss",
                                         "Defense Sacks per Game" = "sacks",
                                         "Interception Yards per Game" = "interceptionYards",
                                         "Interception TDs per Game" = "interceptionTDs",
                                         "Punt Returns per Game" = "puntReturns",
                                         "Punt Return Yards per Game" = "puntReturnYards",
                                         "Punt Return TDs per Game" = "puntReturnTDs",
                                         "Kick Returns per Game" = "kickReturns",
                                         "Kick Return Yards per Game" = "kickReturnYards",
                                         "Kick Return TDs per Game" = "kickReturnTDs",
                                         "Penalties per Game" = "penalties",
                                         "Penalty Yards per Game" = "penaltyYards")),
              selectizeInput("y", "Select Y Variable",
                             choices = c("Yards per Game" = "totalYards",
                                         "Pass Attempts per Game" = "passAttempts",
                                         "Pass Completions per Game" = "passCompletions",
                                         "Net Passing Yards per Game" = "netPassingYards",
                                         "Passing TDs per Game" = "passingTDs",
                                         "Rush Attempts per Game" = "rushingAttempts",
                                         "Rushing Yards per Game" = "rushingYards",
                                         "Rushing TDs per Game" = "rushingTDs",
                                         "First Downs per Game" = "firstDowns",
                                         "Third Down Conversion Rate" = "thirdDownConversionRate",
                                         "Fourth Down Completion Rate" = "fourthDownConversionRate",
                                         "Turnover Differential" = "turnoverDiff",
                                         "Average Time of Possession (Seconds)" = "possessionTime",
                                         "Defense Tackles for Loss per Game" = "tacklesForLoss",
                                         "Defense Sacks per Game" = "sacks",
                                         "Interception Yards per Game" = "interceptionYards",
                                         "Interception TDs per Game" = "interceptionTDs",
                                         "Punt Returns per Game" = "puntReturns",
                                         "Punt Return Yards per Game" = "puntReturnYards",
                                         "Punt Return TDs per Game" = "puntReturnTDs",
                                         "Kick Returns per Game" = "kickReturns",
                                         "Kick Return Yards per Game" = "kickReturnYards",
                                         "Kick Return TDs per Game" = "kickReturnTDs",
                                         "Penalties per Game" = "penalties",
                                         "Penalty Yards per Game" = "penaltyYards")),
              selectizeInput("z", "Filter by Conference",
                             choices = c("No Filter" = "None",
                                         "American Athletic" = "American.Athletic",
                                         "Atlantic Coast" = "ACC",
                                         "Big 12" = "Big.12",
                                         "Big Ten" = "Big.Ten",
                                         "Conference USA" = "Conference.USA",
                                         "FBS Independents" = "FBS.Independents",
                                         "Mid-American" = "Mid.American",
                                         "Mountain West" = "Mountain.West",
                                         "Pac-12" = "Pac.12",
                                         "Southeastern" = "SEC",
                                         "Sun Belt" = "Sun.Belt"))),
              conditionalPanel(
                condition = "input.plotType == 4",
                selectizeInput("x", "Select Variable",
                               choices = c("Yards per Game" = "totalYards",
                                           "Pass Attempts per Game" = "passAttempts",
                                           "Pass Completions per Game" = "passCompletions",
                                           "Net Passing Yards per Game" = "netPassingYards",
                                           "Passing TDs per Game" = "passingTDs",
                                           "Rush Attempts per Game" = "rushingAttempts",
                                           "Rushing Yards per Game" = "rushingYards",
                                           "Rushing TDs per Game" = "rushingTDs",
                                           "First Downs per Game" = "firstDowns",
                                           "Third Down Conversion Rate" = "thirdDownConversionRate",
                                           "Fourth Down Completion Rate" = "fourthDownConversionRate",
                                           "Turnover Differential" = "turnoverDiff",
                                           "Average Time of Possession (Seconds)" = "possessionTime",
                                           "Defense Tackles for Loss per Game" = "tacklesForLoss",
                                           "Defense Sacks per Game" = "sacks",
                                           "Interception Yards per Game" = "interceptionYards",
                                           "Interception TDs per Game" = "interceptionTDs",
                                           "Punt Returns per Game" = "puntReturns",
                                           "Punt Return Yards per Game" = "puntReturnYards",
                                           "Punt Return TDs per Game" = "puntReturnTDs",
                                           "Kick Returns per Game" = "kickReturns",
                                           "Kick Return Yards per Game" = "kickReturnYards",
                                           "Kick Return TDs per Game" = "kickReturnTDs",
                                           "Penalties per Game" = "penalties",
                                           "Penalty Yards per Game" = "penaltyYards")),
                selectizeInput("w", "Select Y Variable",
                               choices = c("Conference" = "conference",
                                           "Bowl Eligibility" = "bowlEligible"))),
            conditionalPanel(
                condition = "input.tabs1 == 'Modeling'",
                sliderInput("trainProp", "Proportion of data to train",
                            min = 0.5, max = 0.9, value = 0.7, step = 0.05))
        ),

        mainPanel(
          tabsetPanel(id = "tabs1", type = "tabs",
                      tabPanel("About",
                               ),
                      tabPanel("Data Exploration",
                               plotOutput("EDAPlot", height = "700")),
                      tabPanel("Modeling", 
                               tabsetPanel(id = "tabs2", type = "tabs",
                                           tabPanel("Modeling Info",
                                                    ),
                                           tabPanel("Model Fitting",
                                                    "Summary of generalized linear model and fit statistics:",
                                                    verbatimTextOutput("glmSummary"),
                                                    "Most important variables in random forest model:",
                                                    plotOutput("rfPlot", height = "700")),
                                           tabPanel("Prediction",
                                                    )))
          )
        )
    )
))
